name: flutter_ts5
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  flutter_tts: ^3.3.3
  speech_to_text: ^5.4.2
  translator: ^0.1.7
  flag: ^6.0.0
  stream_transform: ^2.0.0
  avatar_glow: ^2.0.2
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: cute
      fonts:
        - asset: assets/fonts/cute.ttf
          weight: 700
