class SpeechToTextConstants {
  static const List<String> localeIds = [
    "ar-SA",
    "yue-CN",
    "ca-ES",
    "zh-CN",
    "zh-HK",
    "zh-TW",
    "hr-HR",
    "cs-CZ",
    "da-DK",
    "nl-BE",
    "nl-NL",
    "en-AU",
    "en-CA",
    "en-IN",
    "en-ID",
    "en-IE",
    "en-NZ",
    "en-PH",
    "en-SA",
    "en-SG",
    "en-ZA",
    "en-AE",
    "en-GB",
    "en-US",
    "fi-FI",
    "fr-BE",
    "fr-CA",
    "fr-FR",
    "fr-CH",
    "de-AT",
    "de-DE",
    "de-CH",
    "el-GR",
    "he-IL",
    "hi-IN",
    "hi-IN-translit",
    "hi-Latn",
    "hu-HU",
    "id-ID",
  ];
  // GoogleTranslateConstants.mapLanguageCodeToLanguageName(element.substring(0, 2)) to LanguageName
  // (3,5).tolowercase to flag code
}
