class TextToSpeechConstants {
  static const List<String> textToSpeechLocales = [
    'cs-CZ',
    'nl-BE',
    'fi-FI',
    'he-IL',
    'pt-PT',
    'id-ID',
    'tr-TR',
    'en-US',
    'es-MX',
    'en-IN',
    'ru-RU',
    'sk-SK',
    'zh-CN',
    'de-DE',
    'en-AU',
    'pt-BR',
    'hi-IN',
    'en-IE',
    'sv-SE',
    'th-TH',
    'pl-PL',
    'ja-JP',
    'ar-SA',
    'fr-FR',
    'es-ES',
    'no-NO',
    'hu-HU',
    'en-ZA',
    'fr-CA',
    'el-GR',
    'da-DK',
    'en-GB',
    'zh-TW',
    'ro-RO',
    'zh-HK',
    'it-IT',
    'ko-KR',
    'nl-NL'
  ];
  static const List<String> textToSpeechVoiceName = [
    "Maged (ar-SA)",
    "Zuzana (cs-CZ)",
    "Sara (da-DK)",
    "Anna (de-DE)",
    "Helena (de-DE)",
    "Martin (de-DE)",
    "Melina (el-GR)",
    "Catherine (en-AU)",
    "Gordon (en-AU)",
    "Arthur (en-GB)",
    "Daniel (en-GB)",
    "Martha (en-GB)",
    "Moira (en-IE)",
    "Rishi (en-IN)",
    "Aaron (en-US)",
    "Fred (en-US)",
    "Nicky (en-US)",
    "Samantha (en-US)",
    "Tessa (en-ZA)",
    "Mónica (es-ES)",
    "Paulina (es-MX)",
    "Satu (fi-FI)",
    "Amélie (fr-CA)",
    "Daniel (fr-FR)",
    "Marie (fr-FR)",
    "Thomas (fr-FR)",
    "Carmit (he-IL)",
    "Lekha (hi-IN)",
    "Mariska (hu-HU)",
    "Damayanti (id-ID)",
    "Alice (it-IT)",
    "Hattori (ja-JP)",
    "Kyoko (ja-JP)",
    "O-ren (ja-JP)",
    "Yuna (ko-KR)",
    "Ellen (nl-BE)",
    "Xander (nl-NL)",
    "Nora (no-NO)",
    "Zosia (pl-PL)",
    "Luciana (pt-BR)",
    "Joana (pt-PT)",
    "Ioana (ro-RO)",
    "Milena (ru-RU)",
    "Laura (sk-SK)",
    "Alva (sv-SE)",
    "Kanya (th-TH)",
    "Yelda (tr-TR)",
    "Li-mu (zh-CN)",
    "Ting-Ting (zh-CN)",
    "Yu-shu (Yu-shu)",
    "Sin-Ji (zh-HK)",
    "Mei-Jia (zh-TW)",
    "Alex (en-US)",
  ];

  static String mapVoiceCodeToLocale(String voiceCode) {
    Map<String, String> map = {
      "Maged (ar-SA)": "ar-SA",
      "Zuzana (cs-CZ)": "cs-CZ",
      "Sara (da-DK)": "da-DK",
      "Anna (de-DE)": "de-DE",
      "Helena (de-DE)": "de-DE",
      "Martin (de-DE)": "de-DE",
      "Melina (el-GR)": "el-GR",
      "Catherine (en-AU)": "en-AU",
      "Gordon (en-AU)": "en-AU",
      "Arthur (en-GB)": "en-GB",
      "Daniel (en-GB)": "en-GB",
      "Martha (en-GB)": "en-GB",
      "Moira (en-IE)": "en-IE",
      "Rishi (en-IN)": "en-IN",
      "Aaron (en-US)": "en-US",
      "Fred (en-US)": "en-US",
      "Nicky (en-US)": "en-US",
      "Samantha (en-US)": "en-US",
      "Tessa (en-ZA)": "en-ZA",
      "Mónica (es-ES)": "es-ES",
      "Paulina (es-MX)": "es-MX",
      "Satu (fi-FI)": "fi-FI",
      "Amélie (fr-CA)": "fr-CA",
      "Daniel (fr-FR)": "fr-FR",
      "Marie (fr-FR)": "fr-FR",
      "Thomas (fr-FR)": "fr-FR",
      "Carmit (he-IL)": "he-IL",
      "Lekha (hi-IN)": "hi-IN",
      "Mariska (hu-HU)": "hu-HU",
      "Damayanti (id-ID)": "id-ID)",
      "Alice (it-IT)": "it-IT",
      "Hattori (ja-JP)": "ja-JP",
      "Kyoko (ja-JP)": "ja-JP",
      "O-ren (ja-JP)": "ja-JP",
      "Yuna (ko-KR)": "ko-KR",
      "Ellen (nl-BE)": "nl-BE",
      "Xander (nl-NL)": "nl-NL",
      "Nora (no-NO)": "no-NO",
      "Zosia (pl-PL)": "pl-PL",
      "Luciana (pt-BR)": "pt-BR",
      "Joana (pt-PT)": "pt-PT",
      "Ioana (ro-RO)": "ro-RO",
      "Milena (ru-RU)": "ru-RU",
      "Laura (sk-SK)": "sk-SK",
      "Alva (sv-SE)": "sv-SE",
      "Kanya (th-TH)": "th-TH",
      "Yelda (tr-TR)": "tr-TR",
      "Li-mu (zh-CN)": "zh-CN",
      "Ting-Ting (zh-CN)": "zh-CN",
      "Sin-Ji (zh-HK)": "zh-HK",
      "Mei-Jia (zh-TW)": "zh-TW",
      "Alex (en-US)": "en-US",
    };
    return map[voiceCode] ?? '';
  }

  static String mapVoiceCodeToName(String voiceCode) {
    Map<String, String> map = {
      "Maged (ar-SA)": "Maged",
      "Zuzana (cs-CZ)": "Zuzana",
      "Sara (da-DK)": "Sara",
      "Anna (de-DE)": "Anna",
      "Helena (de-DE)": "Helena",
      "Martin (de-DE)": "Martin",
      "Melina (el-GR)": "Melina",
      "Catherine (en-AU)": "Catherine",
      "Gordon (en-AU)": "Gordon",
      "Karen (Karen)": "Karen",
      "Arthur (en-GB)": "Arthur",
      "Daniel (en-GB)": "Daniel",
      "Martha (en-GB)": "Martha",
      "Moira (en-IE)": "Moira",
      "Rishi (en-IN)": "Rishi",
      "Aaron (en-US)": "Aaron",
      "Fred (en-US)": "Fred",
      "Nicky (en-US)": "Nicky",
      "Samantha (en-US)": "Samantha",
      "Tessa (en-ZA)": "Tessa",
      "Mónica (es-ES)": "Mónica",
      "Paulina (es-MX)": "Paulina",
      "Satu (fi-FI)": "Satu",
      "Amélie (fr-CA)": "Amélie",
      "Daniel (fr-FR)": "Daniel",
      "Marie (fr-FR)": "Marie",
      "Thomas (fr-FR)": "Thomas",
      "Carmit (he-IL)": "Carmit",
      "Lekha (hi-IN)": "Lekha",
      "Mariska (hu-HU)": "Mariska",
      "Damayanti (id-ID)": "Damayanti",
      "Alice (it-IT)": "Alice",
      "Hattori (ja-JP)": "Hattori",
      "Kyoko (ja-JP)": "Kyoko",
      "O-ren (ja-JP)": "O-ren",
      "Yuna (ko-KR)": "Yuna",
      "Ellen (nl-BE)": "Ellen",
      "Xander (nl-NL)": "Xander",
      "Nora (no-NO)": "Nora",
      "Zosia (pl-PL)": "Zosia",
      "Luciana (pt-BR)": "Luciana",
      "Joana (pt-PT)": "Joana",
      "Ioana (ro-RO)": "Ioana",
      "Milena (ru-RU)": "Milena",
      "Laura (sk-SK)": "Laura",
      "Alva (sv-SE)": "Alva",
      "Kanya (th-TH)": "Kanya",
      "Yelda (tr-TR)": "Yelda",
      "Li-mu (zh-CN)": "Li-mu",
      "Ting-Ting (zh-CN)": "Ting-Ting",
      "Sin-Ji (zh-HK)": "Sin-Ji",
      "Mei-Jia (zh-TW)": "Mei-Jia",
      "Alex (en-US)": "Alex",
    };
    return map[voiceCode] ?? "";
  }

  static String mapTextToSpeechVoiceAndLocaleToFlag(String voice) {
    Map<String, String> map = {
      "Maged (ar-SA)": "dz",
      "Zuzana (cs-CZ)": "cz",
      "Sara (da-DK)": "dk",
      "Anna (de-DE)": "de",
      "Helena (de-DE)": "de",
      "Martin (de-DE)": "de",
      "Melina (el-GR)": "gr",
      "Arthur (en-GB)": "gb",
      "Daniel (en-GB)": "gb",
      "Martha (en-GB)": "gb",
      "Moira (en-IE)": "gb",
      "Rishi (en-IN)": "in",
      "Aaron (en-US)": "us",
      "Fred (en-US)": "us",
      "Nicky (en-US)": "us",
      "Samantha (en-US)": "us",
      "Tessa (en-ZA)": "za",
      "Mónica (es-ES)": "es",
      "Paulina (es-MX)": "mx",
      "Satu (fi-FI)": "fi",
      "Amélie (fr-CA)": "ca",
      "Daniel (fr-FR)": "fr",
      "Marie (fr-FR)": "fr",
      "Thomas (fr-FR)": "fr",
      "Carmit (he-IL)": "it",
      "Lekha (hi-IN)": "in",
      "Mariska (hu-HU)": "hu",
      "Damayanti (id-ID)": "id",
      "Alice (it-IT)": "it",
      "Hattori (ja-JP)": "jp",
      "Kyoko (ja-JP)": "jp",
      "O-ren (ja-JP)": "jp",
      "Yuna (ko-KR)": "kr",
      "Ellen (nl-BE)": "an",
      "Xander (nl-NL)": "an",
      "Nora (no-NO)": "no",
      "Zosia (pl-PL)": "pl",
      "Luciana (pt-BR)": "ao",
      "Joana (pt-PT)": "ao",
      "Ioana (ro-RO)": "md",
      "Milena (ru-RU)": "ru",
      "Laura (sk-SK)": "cz",
      "Alva (sv-SE)": "",
      "Kanya (th-TH)": "se",
      "Yelda (tr-TR)": "",
      "Li-mu (zh-CN)": "cn",
      "Ting-Ting (zh-CN)": "cn",
      "Yu-shu (zh-CN)": "cn",
      "Sin-Ji (zh-HK)": "hk",
      "Mei-Jia (zh-TW)": "tw",
      "Alex (en-US)": "us",
    };
    return map[voice] ?? "us";
  }
}
